/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uc15_etapa_01_autofin.Form;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import uc15_etapa_01_autofin.Beans.Fornecedores;
import uc15_etapa_01_autofin.Beans.FornecedoresCSV;
import static uc15_etapa_01_autofin.Beans.FornecedoresCSV.listaFornecedores;

/**
 *
 * @author carlo
 */
public class FornecedoresF extends javax.swing.JFrame {

    /**
     * Creates new form FORNECEDORES
     */
    public FornecedoresF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCNPJ = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        btnCadastar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaFornecedores = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("AutoFin");

        lblFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFornecedor.setText("FORNECEDOR");

        lblNome.setText("Nome:");

        lblCNPJ.setText("C.N.P.J.:");

        lblTelefone.setText("Telefone:");

        lblEndereco.setText("Endereço:");

        btnCadastar.setText("CADASTRAR");
        btnCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastarActionPerformed(evt);
            }
        });

        jLabel7.setText("FORNECEDORES CADASTRADOS");

        TabelaFornecedores.setModel(criaTabelaF());
        jScrollPane1.setViewportView(TabelaFornecedores);

        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair))
                    .addComponent(lblFornecedor)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addComponent(lblCNPJ)
                            .addComponent(lblNome))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(txtTelefone)
                            .addComponent(txtCNPJ)
                            .addComponent(txtNome))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblFornecedor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNPJ)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastarActionPerformed
        Fornecedores f = new Fornecedores();
        try {
            //adicionando novo fornecedor.
            f.setNome(txtNome.getText());
            f.setCnpj(txtCNPJ.getText());
            f.setTelefone(txtTelefone.getText());
            f.setEndereço(txtEndereco.getText());

            // adicionando a lista de fornecedores
            FornecedoresCSV.AdicionarFornecedores(f);

            // Obtendo a tabela.
            DefaultTableModel model = (DefaultTableModel) TabelaFornecedores.getModel();

            // Adicionando um novo fornecedor sem recriar a tabela.
            String[] linha = {
                f.getNome(),
                f.getCnpj(),
                f.getTelefone(),
                f.getEndereco()
            };
            model.addRow(linha);

            // limpando os campos.
            txtNome.setText("");
            txtCNPJ.setText("");
            txtTelefone.setText("");
            txtEndereco.setText("");

        } catch (Exception e) {
            System.out.println("Não Cadastrado.");
        }

    }//GEN-LAST:event_btnCadastarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornecedoresF().setVisible(true);
            }
        });

    }

    public DefaultTableModel criaTabelaF() {

        String[] colunas = {"Nome", "C.N.P.J.", "Telefone", "Endereço"};
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);
        ArrayList<Fornecedores> lista = listaFornecedores();

        for (int i = 0; i < lista.size(); i++) {
            Fornecedores f = lista.get(i);
            String[] linhas = {
                f.getNome(),
                f.getCnpj(),
                f.getTelefone(),
                f.getEndereco()
            };
            tabela.addRow(linhas);
        }
        return tabela;
    }
    
    public void adicionarFornecedor(DefaultTableModel tabela, Fornecedores novoFornecedor) {
    String[] linha = {
        novoFornecedor.getNome(),
        novoFornecedor.getCnpj(),
        novoFornecedor.getTelefone(),
        novoFornecedor.getEndereco()
    };
    tabela.addRow(linha);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaFornecedores;
    private javax.swing.JButton btnCadastar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
